# Generated by Django 3.1.1 on 2020-09-06 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerID', models.CharField(max_length=50)),
                ('CompanyName', models.CharField(max_length=50)),
                ('ContactName', models.CharField(max_length=50)),
                ('ContactTitle', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderID', models.CharField(max_length=50)),
                ('CustomerID', models.CharField(max_length=50)),
                ('EmployeeID', models.IntegerField(verbose_name=10)),
                ('OrderDate', models.CharField(max_length=50)),
                ('RequiredDate', models.CharField(max_length=50)),
                ('ShipVia', models.CharField(max_length=50)),
                ('Freight', models.FloatField(verbose_name=50)),
            ],
            options={
                'db_table': 'Orders',
            },
        ),
    ]
